#   Copyright 2025 NEC Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
version: '3.7'
services:
  ita-ag-oase:
    build:
      target: develop_build
      context: ${ITA_REPO_ROOT:-../../exastro-it-automation-dev}
      secrets:
        - host_certificate_file
    entrypoint: sh -c "sleep infinity;"
    volumes:
      - ..:/workspace/exastro-devcontainer:cached
      - ../vscode/common:/workspace/.vscode:cached
      - ../vscode/exastro-it-automation/ita-by-no-custom/launch.json:/workspace/.vscode/launch.json:cached
      - ${PLATFORM_REPO_ROOT:-../../exastro-platform-dev}:/workspace/exastro-platform-dev:cached
      - ${ITA_REPO_ROOT:-../../exastro-it-automation-dev}:/workspace/exastro-it-automation-dev:cached
      - ${ITA_REPO_ROOT:-../../exastro-it-automation-dev}/ita_root/common_libs:/workspace/exastro-it-automation-dev/ita_root/ita_ag_oase/common_libs:cached
      - ${ITA_REPO_ROOT:-../../exastro-it-automation-dev}/ita_root/messages:/workspace/exastro-it-automation-dev/ita_root/ita_ag_oase/messages:cached
      - ${ITA_REPO_ROOT:-../../exastro-it-automation-dev}/ita_root/agent:/workspace/exastro-it-automation-dev/ita_root/ita_ag_oase/agent:cached
      - ${ITA_REPO_ROOT:-../../exastro-it-automation-dev}/ita_root/ita_ag_oase:/exastro:cached
      - ${ITA_REPO_ROOT:-../../exastro-it-automation-dev}/ita_root/common_libs:/exastro/common_libs:cached
      - ${ITA_REPO_ROOT:-../../exastro-it-automation-dev}/ita_root/messages:/exastro/messages:cached
      - ${ITA_REPO_ROOT:-../../exastro-it-automation-dev}/ita_root/agent:/exastro/agent:cached
      - ~/.netrc:/home/app_user/.netrc
      - ~/.gitconfig:/home/app_user/.gitconfig
      - ~/.config/git/ignore:/home/app_user/.config/git/ignore
      - ${HOST_CERTIFICATE_FILE:-/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem}:/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
      - /usr/share/pki/ca-trust-source/anchors/UserRootCertificate.crt:/etc/ssl/certs/ca-certificates.crt
      - /mnt/mainte/talisman/.talismanrc:/mnt/mainte/talisman/.talismanrc
      - ${TALISMAN_HOME}:${TALISMAN_HOME}
      - /var/run/docker.sock:/var/run/docker.sock
      - ../.vscode_extensions/vscode-server/extensions:/home/app_user/.vscode-server/extensions
      - ../.vscode_extensions/vscode-server-insiders/extensions:/home/app_user/.vscode-server-insiders/extensions
    environment:
      - DEVCONTAINER_MAIN_SERVICE=${DEVCONTAINER_MAIN_SERVICE:-}
      - CONTAINER_NAME=ita-ag-oase
      - SOURCE_ROOT=/workspace/exastro-it-automation-dev/ita_root/ita_ag_oase
      - HTTP_PROXY=${HTTP_PROXY}
      - http_proxy=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - https_proxy=${HTTPS_PROXY}
      - NO_PROXY=127.0.0.1,localhost,keycloak,platform-auth,platform-api,platform-web,ita-api-admin,ita-api-organization,ita-api-oase-receiver,ita-api-ansible-execution-receiver,ita-web-server,${NO_PROXY}
      - no_proxy=127.0.0.1,localhost,keycloak,platform-auth,platform-api,platform-web,ita-api-admin,ita-api-organization,ita-api-oase-receiver,ita-api-ansible-execution-receiver,ita-web-server,${NO_PROXY}
      # - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
      # - SSL_CERT_DIR=/etc/ssl/certs
      - NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt
      - REQUESTS_CA_BUNDLE=/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem


