#!/bin/bash
#   Copyright 2025 NEC Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
echo "START $(basename $0)"

BASE_DIR=$(realpath $(dirname $0))
REPO_DIR=$(realpath ${BASE_DIR}/..)

MONGO_ADMIN_USER=$(sed -n -e 's/#.*$//' -e 's/^MONGO_ADMIN_USER=//p' "${REPO_DIR}/docker-compose/.env")
MONGO_ADMIN_PASSWORD=$(sed -n -e 's/#.*$//' -e 's/^MONGO_ADMIN_PASSWORD=//p' "${REPO_DIR}/docker-compose/.env")

mkdir -p ${BASE_DIR}/.build

python3 <<__EOF__
import os, json, string, configparser

COMMENT='/* This file is automatically generated. Do not modify this file directly. */\n'

with open('${BASE_DIR}/build.conf.json') as fp_build_confs:
    build_confs = json.load(fp_build_confs)

for build_conf in build_confs:

    output_path=f'${BASE_DIR}/.build/{build_conf["service_name"]}'
    os.makedirs(output_path, exist_ok=True)

    for outfile, tmplfile in build_conf["build_files"].items():

        if os.path.splitext(tmplfile)[1] == ".template":

            with open(f'${BASE_DIR}/templates/{tmplfile}') as fp_tmpl:
                tmpl = fp_tmpl.read()

            build_conf['MONGO_ADMIN_USER'] = '${MONGO_ADMIN_USER}'
            build_conf['MONGO_ADMIN_PASSWORD'] = '${MONGO_ADMIN_PASSWORD}'

            result = string.Template(tmpl).safe_substitute(build_conf)

            with open(f'{output_path}/{outfile}', 'w') as fp:
                fp.write(COMMENT)
                fp.write(result)

        else:
            with open(f'${BASE_DIR}/templates/{tmplfile}') as fp_tmpl:
                tmpl = fp_tmpl.read()

            with open(f'{output_path}/{outfile}', 'w') as fp:
                fp.write(COMMENT)
                fp.write(tmpl)

__EOF__

echo "END $(basename $0)"
