services:
  ssh-server-1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - http_proxy=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - https_proxy=${HTTPS_PROXY}
        - SSH_USER_NAME=${SSH_SERVER_1_USER_NAME:-sshuser1}
        - SSH_USER_PASSWORD=${SSH_SERVER_1_USER_PASSWORD:-password}
      secrets:
        - host_certificate_file
    environment:
        - HTTP_PROXY=${HTTP_PROXY}
        - http_proxy=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - https_proxy=${HTTPS_PROXY}
        - no_proxy=${NO_PROXY}
        - SSL_CERT_FILE=/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
        - REQUESTS_CA_BUNDLE=/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
    volumes:
      - ${HOST_CERTIFICATE_FILE:-/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem}:/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
    privileged: true
    tmpfs:
      - /run
      - /run/lock
    ports:
      - "${SSH_SERVER_1_SSH_PORT:-2122}:22"
      - "${SSH_SERVER_1_HTTP_PORT:-8180}:80"
    restart: unless-stopped
    networks:
      - exastro

  ssh-server-2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - http_proxy=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - https_proxy=${HTTPS_PROXY}
        - SSH_USER_NAME=${SSH_SERVER_2_USER_NAME:-sshuser2}
        - SSH_USER_PASSWORD=${SSH_SERVER_2_USER_PASSWORD:-password}
      secrets:
        - host_certificate_file
    environment:
        - HTTP_PROXY=${HTTP_PROXY}
        - http_proxy=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - https_proxy=${HTTPS_PROXY}
        - no_proxy=${NO_PROXY}
        - SSL_CERT_FILE=/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
        - REQUESTS_CA_BUNDLE=/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
    volumes:
      - ${HOST_CERTIFICATE_FILE:-/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem}:/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
    privileged: true
    tmpfs:
      - /run
      - /run/lock
    ports:
      - "${SSH_SERVER_2_SSH_PORT:-2222}:22"
      - "${SSH_SERVER_2_HTTP_PORT:-8280}:80"
    restart: unless-stopped
    networks:
      - exastro

  ssh-server-3:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - http_proxy=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - https_proxy=${HTTPS_PROXY}
        - SSH_USER_NAME=${SSH_SERVER_3_USER_NAME:-sshuser3}
        - SSH_USER_PASSWORD=${SSH_SERVER_3_USER_PASSWORD:-password}
      secrets:
        - host_certificate_file
    environment:
        - HTTP_PROXY=${HTTP_PROXY}
        - http_proxy=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - https_proxy=${HTTPS_PROXY}
        - no_proxy=${NO_PROXY}
        - SSL_CERT_FILE=/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
        - REQUESTS_CA_BUNDLE=/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
    volumes:
      - ${HOST_CERTIFICATE_FILE:-/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem}:/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
    privileged: true
    tmpfs:
      - /run
      - /run/lock
    ports:
      - "${SSH_SERVER_3_SSH_PORT:-2322}:22"
      - "${SSH_SERVER_3_HTTP_PORT:-8380}:80"
    restart: unless-stopped
    networks:
      - exastro

networks:
  exastro:
    name: "exastro_${NETWORK_ID}"

secrets:
  host_certificate_file:
    file: ${HOST_CERTIFICATE_FILE:-/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem}
